language: node_js
os: linux
dist: focal
node_js:
  - 14
jobs:
  include:
    - stage: Build
      install:
        - npm i --ignore-scripts --production
      script:
        - npm run build
    - stage: Check code quality
      install:
        - npm i --ignore-scripts --also=dev
      script:
        - npm run lint
