language: node_js
node_js:
    - 12
jobs:
    include:
        - stage: Build
        install:
            - npm i --ignore-scripts --also=dev
        script:
            - npm run build
        - stage: Check code quality
        script:
            - npm run lint
