version: "3"
services:
  bird-bot:
    container_name: "pis-bot"
    image: "pterodactylinstaller/pis-bot:latest"
    environment:
      # Your bots token
      - TOKEN=
      # Your bots prefix
      - PREFIX=!
      # Embet color (RED, BLUE, #4f86f7)
      - EMBED_COLOR=BLUE
    restart: unless-stopped
